import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewportSize: { width: 1060, height: 800 } });
await p.goto('http://localhost:3119/zzp', { waitUntil: 'networkidle' });
await p.waitForTimeout(700);
const row = await p.$('tr.closing');
if (row) await row.scrollIntoViewIfNeeded();
await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/C-closing.png' });
await b.close();
