import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewportSize: { width: 900, height: 900 } });
await p.goto('http://localhost:3127/', { waitUntil: 'networkidle' });
await p.waitForTimeout(600);
await p.click('.choice');
await p.waitForTimeout(400);
await p.click('text=각자 낸 금액 입력');
await p.waitForTimeout(500);
const rows = p.locator('table.book input');
await rows.nth(0).fill('관우'); await rows.nth(1).fill('52000');
await rows.nth(2).fill('민수'); await rows.nth(3).fill('12000');
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/QD.png', fullPage: true });
await b.close();
